# Line length
max_width = 100

# comments
comment_width               = 100
format_code_in_doc_comments = true
wrap_comments               = true

# imports
group_imports       = "StdExternalCrate"
imports_granularity = "Item"
reorder_imports     = true

# vertical alignment thresholds
enum_discrim_align_threshold = 50
struct_field_align_threshold = 50

# other formatting
fn_single_line             = true
match_block_trailing_comma = true
